### ISSUE TITLE
RuntimeError: shape '[1, 1, 14, 16, 13]' is invalid for input of size 3120

### ISSUE THREAD

**Issue by SysDevHayes** [Yaoyi-Li/HOP-Matting#4]
Dear @Yaoyi-Li,

Thank you so much for this great work. I'm training this on my custom dataset. With all 512x512 images. The model seems to worked well. However, there are images where I received this error:
`RuntimeError: shape '[1, 1, 14, 16, 13]' is invalid for input of size 3120`

The problem came from [this line](https://github.com/Yaoyi-Li/HOP-Matting/blob/4ac22d92b5432734ffe416cf2c0a99fb730d0c04/networks/ops.py#L419) and [this line](https://github.com/Yaoyi-Li/HOP-Matting/blob/4ac22d92b5432734ffe416cf2c0a99fb730d0c04/networks/ops.py#L421) in the code. Some images worked well, but there are a lot of images that encountered this error. 

Can you please give me a small guide on how to fix it? Thank you so much!

**Comment by SysDevHayes** [comment]
A bit more information, since you have not yet provided the pretrained model "model_best_resnet34_D_nomixup.pth.tar", I used the ResNet34_En_nomixup model from your previous work (GCA-Matting) and it seems to work, at least, the training ran flawlessly. I'm not sure if that is also a source of that problem.

**Comment by SysDevHayes** [comment]
@Yaoyi-Li I tested your pretrained model HOP-9x9-RI-all-data.pth and this model also encountered exactly the same problem. Can you please give me a guide on how to fix it? Thank you so much!

**Comment by Yaoyi-Li** [comment]
Did you add the training dataloader by yourself? I think you can check whether the size of input image is divisible by 32 first. And the input image should be larger than (15\*32, 15\*32). If your image is smaller than (480, 480), you can pad the image or reduce the default `embed_radius`

**Comment by SysDevHayes** [comment]
Thank you for your reply. I did add the training data load myself, using the training from your previous work GCA-Matting. All images in my training data have the size of 512x512. I wrote a piece of code to resize the input images to be divisible by 32. However, that problem still persists. I tested with your pretrained model and it happened exactly the same. 

Please find attached one of the image and corresponding trimap that I used to test. Please kindly note that all input images were resize to be divisible by 32. 

The error was:
`RuntimeError: shape '[1, 13, 1, 12, 12]' is invalid for input of size 2160`

![new_img](https://user-images.githubusercontent.com/46409458/98572501-49274700-22e8-11eb-80f6-6c51cb4779dc.jpg)
![new_trimap](https://user-images.githubusercontent.com/46409458/98572513-4cbace00-22e8-11eb-8fd8-d409ebb76cb0.png)

**Comment by SysDevHayes** [comment]
@Yaoyi-Li Seems to be a minor bug in my code. Thank you so much. I figured it out.
